### ISSUE TITLE
Promote PostgresSQL 9.5 to default in DSpace role

### ISSUE THREAD

**Issue by alanorth** [ilri/rmg-ansible-public#40]
Once the Ubuntu 16.04 + Java 8 + Tomcat 8 + DSpace 5.5 stack is all ready, the DSpace role should default to PostgreSQL 9.5. Hosts needing PostgreSQL 9.3 can override the PostgreSQL version in their host_vars:

```
pg_version: 9.3
```

**Comment by oguya** [comment]
Good idea! Any group interested in 9.5 should default to it in it's group_vars or something of the sort. We still have a couple of hosts(ankole & some 2 more linodes) still running 9.3.

**Comment by alanorth** [comment]
I'm getting ready to upgrade the DSpace role from 9.3 to 9.5. In addition to setting a new default `pg_version` for the role, I am wondering how to ensure that we have only one PostgreSQL version installed.

Hosts previously using the PostgreSQL role will currently have these 9.3 packages installed:

- postgresql-9.3
- postgresql-client-9.3
- postgresql-contrib-9.3
- optionally: postgresql-server-dev-9.3

Should I just remember to remove them manually before I run the playbook, or should we include a cleanup task with some Jinja math, something like:

```
- name: Install postgresql
  apt: name={{ item }} update_cache=yes state=absent
  with_items:
    - postgresql-{{ pg_version - 0.1 }}
    - postgresql-client-{{ pg_version - 0.1 }}
    - postgresql-contrib-{{ pg_version - 0.1 }}
    - postgresql-{{ pg_version - 0.2 }}
    - postgresql-client-{{ pg_version - 0.2 }}
    - postgresql-contrib-{{ pg_version - 0.2 }}
  tags: packages
```

Assuming `pg_version` was 9.5, then I think that would get 9.4 and 9.3 and remove them...
